project:
  type: website

website:
  title: "Luis Paese"
  site-url: "https://paeselhz.github.io/"
  page-navigation: true
  cookie-consent: true
  google-analytics: "G-6QP6SPK8HL"
  twitter-card: 
    creator: "@paeselhz"
    card-style: summary_large_image
  favicon: navbar/favicon.ico
  page-footer:
    center:
      - icon: github
        href: https://github.com/paeselhz/
      - icon: twitter
        href: https://twitter.com/paeselhz
      - icon: envelope
        href: mailto:lhzpaese@gmail.com
    left: "Developed by LHZ Paese. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/).<br>Powered by [Quarto](https://quarto.org)"
  navbar:
    pinned: true
    left: 
      - href: posts/index.qmd
        text: Blog
      - href: navbar/research.qmd
        text: Research
      - href: projects/index.qmd
        text: Projects
    right:
      - href: navbar/about.qmd
        text: About Me
      - href: navbar/resume.pdf
        text: CV
      - icon: github
        aria-label: GitHub
        href: "https://github.com/paeselhz"
      - icon: linkedin
        aria-label: LinkedIn
        href: "https://www.linkedin.com/in/lhzpaese/"
      - icon: twitter
        aria-label: Twitter
        href: "https://twitter.com/paeselhz"

format:
  html:
    smooth-scroll: true
    theme: [flatly, styles.scss]
    backgroundcolor: '#f4f1ed'
    css: styles.css
    toc: true
    include-in-header: [meta.html]
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/paeselhz\.github\.io\/**'
    code-link: true
    