<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Luis HZ Paese">
<meta name="dcterms.date" content="2018-08-24">

<title>Luis Paese - Google Cloud Platform - How-to deploy Shiny Server and RStudio Server</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../navbar/favicon.ico" rel="icon">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6QP6SPK8HL"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6QP6SPK8HL', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  });
});
</script> 
  
<style>html{ scroll-behavior: smooth; }</style>
<!--<base target="_blank">-->
<!-- Primary Meta Tags -->
<title>Luis Paese</title>
<meta name="title" content="Luis Paese">
<meta name="description" content="Welcome to my website! Here I write about Data Science and MLOps.">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://paeselhz.github.io/">
<meta property="og:title" content="Luis Paese - Google Cloud Platform - How-to deploy Shiny Server and RStudio Server">
<meta property="og:description" content="Welcome to my website! Here I write about Data Science and MLOps.">
<!--<meta property="og:image" content="">-->

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://paeselhz.github.io/">
<meta property="twitter:title" content="Luis Paese">
<meta property="twitter:description" content="Welcome to my website! Here I write about Data Science and MLOps.">
<!--<meta property="twitter:image" content="">-->


<link rel="stylesheet" href="../../styles.css">
<meta name="twitter:title" content="Luis Paese - Google Cloud Platform - How-to deploy Shiny Server and RStudio Server">
<meta name="twitter:description" content="Guide to deploying RStudio Open Source and Shiny Server Open Source at GCP">
<meta name="twitter:creator" content="@paeselhz">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Luis Paese</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../posts/index.html">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../navbar/research.html">
 <span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects/index.html">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../recipes/index.html">
 <span class="menu-text">Recipes</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../navbar/about.html">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../navbar/resume.pdf">
 <span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/paeselhz"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/lhzpaese/"><i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/paeselhz"><i class="bi bi-twitter" role="img" aria-label="Twitter">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#setting-up-the-gcp-vm-instance" id="toc-setting-up-the-gcp-vm-instance" class="nav-link" data-scroll-target="#setting-up-the-gcp-vm-instance">Setting up the GCP VM instance</a>
  <ul class="collapse">
  <li><a href="#creating-a-vm-instance" id="toc-creating-a-vm-instance" class="nav-link" data-scroll-target="#creating-a-vm-instance">Creating a VM Instance</a></li>
  <li><a href="#setting-up-vm-connections-before-installing-rstudio-or-shiny-server" id="toc-setting-up-vm-connections-before-installing-rstudio-or-shiny-server" class="nav-link" data-scroll-target="#setting-up-vm-connections-before-installing-rstudio-or-shiny-server">Setting up VM connections before installing RStudio or Shiny Server</a>
  <ul class="collapse">
  <li><a href="#allowing-ports-for-rstudio-server-and-shiny-server" id="toc-allowing-ports-for-rstudio-server-and-shiny-server" class="nav-link" data-scroll-target="#allowing-ports-for-rstudio-server-and-shiny-server">Allowing ports for Rstudio Server and Shiny Server</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#installing-r-on-your-virtual-machine" id="toc-installing-r-on-your-virtual-machine" class="nav-link" data-scroll-target="#installing-r-on-your-virtual-machine">Installing R on your Virtual Machine</a></li>
  <li><a href="#installing-rstudio-server-on-your-virtual-machine" id="toc-installing-rstudio-server-on-your-virtual-machine" class="nav-link" data-scroll-target="#installing-rstudio-server-on-your-virtual-machine">Installing RStudio Server on your Virtual Machine</a></li>
  <li><a href="#installing-shiny-server-on-your-virtual-machine" id="toc-installing-shiny-server-on-your-virtual-machine" class="nav-link" data-scroll-target="#installing-shiny-server-on-your-virtual-machine">Installing Shiny Server on your Virtual Machine</a></li>
  <li><a href="#final-remarks" id="toc-final-remarks" class="nav-link" data-scroll-target="#final-remarks">Final Remarks</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Google Cloud Platform - How-to deploy Shiny Server and RStudio Server</h1>
<p class="subtitle lead">Guide to deploying RStudio Open Source and Shiny Server Open Source at GCP</p>
  <div class="quarto-categories">
    <div class="quarto-category">RStudio</div>
    <div class="quarto-category">Shiny</div>
    <div class="quarto-category">Google Cloud Platform</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Luis HZ Paese </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 24, 2018</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<blockquote class="blockquote">
<p>Disclaimer: This guide was written before the dissemination of the use of containers in Cloud Environments and I maintained it only until 2018, after that period, it became much easier to deploy this applications using containers. However, this guide is still being used by people that desire to deploy their own applications of RStudio Server Open Source and Shiny Server Open Source, without the use of containers.</p>
</blockquote>
<p>The original post can be found <a href="https://github.com/paeselhz/RStudio-Shiny-Server-on-GCP">here</a>. <img src="https://img.shields.io/github/stars/paeselhz/RStudio-Shiny-Server-on-GCP?style=social"></p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>With the advance of cloud computing, and the higher accessibility given to this platforms, there’s an uprising trend to use the existing cloud services, and integrating it with one of the greatest statistical software in the market: R!</p>
<p>This guide is a step-by-step way to show how to configure the Google Cloud Platform as easy as possible, and how to set up two of the most used features of R in the cloud: RStudio Server - To develop your code with an easy to use interface; and Shiny Server, to deploy amazing data visualization websites easily.</p>
</section>
<section id="setting-up-the-gcp-vm-instance" class="level1">
<h1>Setting up the GCP VM instance</h1>
<p>In order to use the Google services, you need to signup for the cloud feature (<code>cloud.google.com</code>), with a valid billing account. Many cloud services such as GCP, Amazon Web Services and others offer Free Tier Machines, that are often offered for a year.</p>
<p>After logging in to your Google account, and setting up your google cloud console. There are a few steps to take that make the experience of using cloud computing easier. First of all, you’ll need a few applications to connect to your server, download the desirable authentications to operate and transfer files from the local machine to your Google cloud compute engine.</p>
<p>The applications needed are:</p>
<ul>
<li>WinSCP: A file transfer feature that allows transitioning of files from/to your server easily and safely. (https://winscp.net/eng/download.php)</li>
<li>Putty: The terminal connection that allows the execution of code inside your virtual machine. (http://www.putty.org/)</li>
<li>Google Cloud SDK: The Google service management that allows the import of private keys to your server, and that helps manage firewall rules. (https://cloud.google.com/sdk/docs/quickstart-windows)</li>
</ul>
<section id="creating-a-vm-instance" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-vm-instance">Creating a VM Instance</h2>
<p>Since the installation of the desired software is complete, now you need to create your first VM instance. At the side panel of Google Cloud Platform’s Console, you’ll find the Compute Engine menu, and inside that, the VM Instances Option. Clicking on that you’ll be prompted to create or import a Virtual Machine. Select Create, and you’ll be taken to the following page:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="vm_instance_1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">VM Instance Creation</figcaption><p></p>
</figure>
</div>
<p>At this section, you can choose a name for your virtual machine, later you can select where that VM instance will be hosted, the cheaper places are in the US, but given the distance, you might find the connection “laggy”. After picking the name and the zone, select what kind of instance you’ll be holding. This will be given by your use of technologies, if you’ll need lots of memory or lots of processing cores, here’s where you’ll choose it. The price per month will depend on this configurations.</p>
<p>After choosing the kind of horsepower that will equip your virtual machine, you can choose what kind of Operational System will come installed with it. For this project, I will choose Ubuntu 18.04, the newest LTS version of this OS available. Also, while choosing the OS, you can choose what kind of storage you’ll need. For this project, we will choose 20 GBs hosted at an SSD, this choice can be made given the amount of space you need, for simple projects 20GB should be more than enough. This gives us speed and reliability.</p>
<p>Later, the last thing to do is allow HTTP traffic and create the VM instance. This process might take a while. If all went correctly you probably will see something like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="vm_instance_2.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Created VM</figcaption><p></p>
</figure>
</div>
</section>
<section id="setting-up-vm-connections-before-installing-rstudio-or-shiny-server" class="level2">
<h2 class="anchored" data-anchor-id="setting-up-vm-connections-before-installing-rstudio-or-shiny-server">Setting up VM connections before installing RStudio or Shiny Server</h2>
<p>Now, you have a Virtual Machine hosted at Google Cloud Platform! At the external IP that is given to you, you can access different ports on that server, hosted at the cloud. But before we start installing R, Rstudio Server and Shiny Server, we need to create a secure connection between your local machine and the hosted Virtual Machine.</p>
<p>To do that you click on the arrow, at the left of SSH button, as shown below, and select “View gcloud Command”:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="vm_instance_ssh.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">VM SSH authentication</figcaption><p></p>
</figure>
</div>
<p>This step will generate a line of code that will be used to create a secure connection between your local machine, and your server. Do not share this snippet with anyone, since it can be used to connect to your server. Copy this line of code, and paste at the Google SDK app that we downloaded before.</p>
<p>It’ll prompt you to authenticate your connection with Google, before downloading the private key. After that is done, you’ll be able to find the private key at your Users folder, inside the <code>/.ssh</code> folder. If the authentication went correctly, the gcloud SDK will open a Putty session, running the Linux distro that is hosted by the virtual machine, you can close this since we’ll authenticate our connection through WinSCP.</p>
<p>After that is done, you’ll open WinSCP, and create a new connection. At the Host you’ll insert the EXTERNAL IP ADDRESS that is given by Google to your server, the door will remain 22, and the user will be the name of your Google account user. After filling this parts, leave the password blank, and click on the Advanced… box, right below the password field. Inside of the Advanced Settings, go to SSH &gt; Authentication at the map to your left. At the field that asks for your Private Key File, you’ll click browse, and search for the <code>"google_compute_engine.ppk"</code> file that is stored in your <code>User/.ssh/</code> folder.</p>
<p>If this setting went successfully, you’ll be able to see at the left portion of your screen the files of your local machine and at the right side of your monitor, the files of your virtual machine. Success, we have managed to enter the files at the Google cloud server!</p>
<section id="allowing-ports-for-rstudio-server-and-shiny-server" class="level3">
<h3 class="anchored" data-anchor-id="allowing-ports-for-rstudio-server-and-shiny-server">Allowing ports for Rstudio Server and Shiny Server</h3>
<p>Even though we haven’t installed yet the RStudio nor the Shiny Server, we can allow the connection ports of the server that will be used later by this applications to connect via browser to our server.</p>
<p>In order to do that, you’ll open the GCloud SDK feature, and paste the following codes: - For the RStudio Connection:</p>
<pre><code>sudo gcloud compute firewall-rules create rstudio-conn --allow=tcp:8787</code></pre>
<ul>
<li>For the Shiny Server Connection:</li>
</ul>
<pre><code>sudo gcloud compute firewall-rules create shiny-conn --allow=tcp:3838</code></pre>
<p>Done! Now you’ll be able to access the hosted process by RStudio and Shiny Server</p>
</section>
</section>
</section>
<section id="installing-r-on-your-virtual-machine" class="level1">
<h1>Installing R on your Virtual Machine</h1>
<p>Now, we have the configuration, and connection setup, we need to open WinSCP, and open Putty (Ctrl+P), to use the terminal command line at our virtual machine.</p>
<p>Before installing any applications, make sure that your machine is up-to-date running this commands:</p>
<pre><code>sudo apt-get update
sudo apt-get upgrade</code></pre>
<p>After it went successfully, you’ll need to add the R repository to the sources.list file, so that the Ubuntu will know where to fetch the application. The code chunk below adds a line to the repository list, then passes a key for the Ubuntu server to download R, updates the existing packages, and installs r-base and r-base dev.</p>
<pre><code>sudo sh -c 'echo "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/" &gt;&gt; /etc/apt/sources.list'
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo apt-get update
sudo apt-get install r-base r-base-dev</code></pre>
<p>A few features won’t work using only the r-base, since the packages are based on other programs as well, so to cover a few of those, below are the codes used to install the software needed.</p>
<ol type="1">
<li>Spatial Libraries:</li>
</ol>
<pre><code>sudo apt-get install libgeos-dev libproj-dev libgdal-dev</code></pre>
<ol start="2" type="1">
<li>Tidyverse Universe:</li>
</ol>
<pre><code>sudo apt-get install libcurl4-openssl-dev libssl-dev libxml2-dev</code></pre>
<p>Now, you can run R on your virtual machine. Since the user logged in does not have root permissions, we advise running R with the following code, so that the installation of packages will be smoother this way.</p>
<pre><code>sudo -i R</code></pre>
<p>Now that we have R open at the terminal of our virtual machine, we might as well install a few packages that will be useful with Shiny, such as the shiny package, the RMarkdown package, and dplyr.</p>
<p>To do that, at the command line in R type:</p>
<pre><code>install.packages(c('shiny', 'rmarkdown', 'dplyr'))</code></pre>
<p>Select the desired mirror, and download the aforementioned packages. This process might take a while.</p>
<p>Once installation is complete, leave the R command line:</p>
<pre><code>quit()</code></pre>
</section>
<section id="installing-rstudio-server-on-your-virtual-machine" class="level1">
<h1>Installing RStudio Server on your Virtual Machine</h1>
<p>Now, we have R installed on our virtual machines, and we need to install the RStudio server in order to access it through the external ip address at door 8787(which is default). To do that, we need to install gdebi first, which is used to install both Shiny Server and Rstudio Server.</p>
<p>The following code will install gdebi, download the .deb file that contains the RStudio server file, and execute it.</p>
<pre><code>sudo apt-get install gdebi-core
wget https://download2.rstudio.org/rstudio-server-1.1.456-amd64.deb
sudo gdebi rstudio-server-1.1.456-amd64.deb</code></pre>
<p>This execution will prompt you to agree with the installation of RStudio server, and if all went well, you’ll see that the rstudio-server process is running.</p>
<p>To verify if the installation went correctly, access <code>http://your_external_ip:8787</code>. If everything is fine, you’ll find this screen:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="rstudio_log_page.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">RStudio Server Login Page</figcaption><p></p>
</figure>
</div>
<p>After this, you’ll need to create a user to use the RStudio hosted on your virtual machine, so you go back to the Linux terminal, and type:</p>
<pre><code>sudo adduser YOUR_USER_NAME</code></pre>
<p>This process will prompt you to create a password and set a few parameters for this new user. But after that, you’ll be able to use YOUR_USER_NAME and the chosen password to login to RStudio Server. If this process went well, you’ll find the RStudio interface at your browser.</p>
<p>NOTE: Remember, the Rstudio is not running with root permissions, so to install new packages and save files at different folders, you’ll need to do that using the Linux terminal, with the help of the <code>sudo</code> command.</p>
</section>
<section id="installing-shiny-server-on-your-virtual-machine" class="level1">
<h1>Installing Shiny Server on your Virtual Machine</h1>
<p>The process of installation of the shiny server is pretty similar to the one of the RStudio Server, the difference is the door that the process will be hosted, which by default is 3838, and that the creation of files inside shiny-server is dependent on root permissions, so every modification must be dealt with a <code>sudo</code> prefix.</p>
<p>To install the Shiny Server, we’ll install the gdebi to execute the installation, if you already have installed gdebi before, you can discard the first line. The second line is to download the file of installation, and the third one is to execute the installation.</p>
<pre><code>sudo apt-get install gdebi-core
wget https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.7.907-amd64.deb
sudo gdebi shiny-server-1.5.7.907-amd64.deb</code></pre>
<p>As well as with the RStudio Server installation, you’ll be prompted to agree with the installation. If it all went successfully you’ll notice a shiny-server process up and running.</p>
<p>To verify if the installation is complete, you can access <code>http://your_external_ip:3838</code>. If everything is fine, you’ll see this screen:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="shiny_welcome.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Shiny Server Welcome Page</figcaption><p></p>
</figure>
</div>
<p>NOTE: Even though this might not be considered as a good practice in development, to make your life easier while dealing with shiny apps in construction, you might set full edit permissions to the folder containing shiny-server folders using the following command:</p>
<pre><code>sudo chmod 777 -R /srv/shiny-server/</code></pre>
</section>
<section id="final-remarks" class="level1">
<h1>Final Remarks</h1>
<p>This project is in constant updates and modifications, so you might notice a few changes since the last access or the last commit. If is there any trouble with any of the installations above, make sure to check the documentation of each feature, to ensure that everything is working fine, and as is supposed to work.</p>
<p>The links below are easy links to the documentation for each of the features revised by this post.</p>
<ul>
<li><a href="https://cloud.google.com/docs/">Google Cloud Compute Documentation</a></li>
<li><a href="http://docs.rstudio.com/ide/server-pro/">RStudio Server Documentation</a></li>
<li><a href="http://docs.rstudio.com/shiny-server/">Shiny Server Documentation</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp(/^(?:http:|https:)\/\/paeselhz\.github\.io\/**/);
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Developed by LHZ Paese. License: <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA 2.0</a>.<br>Powered by <a href="https://quarto.org">Quarto</a></div>   
      <div class="nav-footer-center">
        <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/paeselhz/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/paeselhz">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:lhzpaese@gmail.com">
      <i class="bi bi-envelope" role="img">
</i> 
    </a>
  </li>  
</ul>
      <div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
  </div>
</footer>



<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>